### PR TITLE
CND generated from AEM 6.5.7.0 with https://github.com/apache/sling-org-apache-sling-jcr-webconsole

### PR DESCRIPTION
**Pull request by stefanseifert**

### CODE REVIEW

**Comment by stefanseifert** [comment]
the new release 6.5.7.0 is not yet available on maven central - can you publish it there?
https://repo1.maven.org/maven2/biz/netcentric/aem/aem-nodetypes/

**Comment by kwin** [comment]
Thanks for the hint, something went wrong with releasing the staging repository. Just triggered it again. Should hit Maven Central in the next hour.

**Comment by kwin** [comment]
It might take a bit longer than usual, due to the outage of oss.sonatype.com yesterday (https://status.maven.org/incidents/pbd519yh4h3r?u=kgrxvpyrw7k5). Seems that the job queue is still quite long...

**Comment by stefanseifert** [comment]
it's there, thanks

**Pull request merged**
